services:
    warsaw-container:
        build:
            context: .
            dockerfile: Dockerfile
        image: warsaw-container:latest
        container_name: warsaw-container
        privileged: true
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=${DISPLAY}
            - LC_ALL=en_US.UTF-8
        ipc: host
        cgroup: host
        tty: true
        stdin_open: true
        networks:
            - warsaw-network
        restart: unless-stopped

networks:
    warsaw-network:
        driver: bridge
