services:
  warsaw:
    build:
      context: .
      dockerfile: Dockerfile
    image: warsaw-container
    container_name: warsaw
    privileged: true
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /sys/fs/cgroup:/sys/fs/cgroup:ro  # Necessário para o systemd
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    command: ["/sbin/init"]  # Inicia o systemd como PID 1
    #command: ["tail", "-f", "/dev/null"]